// GENERATED — do not edit. Source: contracts/claims/registry.json
// Regenerate: ui/tools/gen-claims-qml.py  ·  CI fails if this drifts (--check).
//
// The ADR-012 claims registry as a QML value object: the walkthrough's four
// questions as data, not prose in a delegate. `kind` is closed
// (protects | others-leak | gap); a gap's `status` is closed
// (shipped | specified | partial | none); a protects/gap claim's `credibility`
// is closed (imperative | motivational | exposed | not-applicable) and names its
// `party` when someone's conduct — or view — is what remains. Every field here was resolved against
// a real requirement and a real test by scripts/check-claims-registry.py before
// it reached this file — an empty field would have failed that gate, where prose
// in a view would have read fine and been wrong.

import QtQuick

QtObject {
    id: root

    readonly property var steps: [
        { id: "open-room", title: qsTr("Open the room"), summary: qsTr("A conversation is created as an end-to-end encrypted room over the delivery transport. Who is in the room is the security boundary; everything below happens inside it.") },
        { id: "propose", title: qsTr("Propose the transaction"), summary: qsTr("A member proposes an effect (what should happen). The client derives the materialization (the exact bytes that would be signed) and shows both, so the room reviews the effect while the machine commits to the materialization.") },
        { id: "collect", title: qsTr("Collect approvals"), summary: qsTr("The proposal gathers authorizations round by round, as the driver's policy describes. Each contribution is an authored, room-authenticated message folded into the intent's state.") },
        { id: "executable", title: qsTr("Ready to submit"), summary: qsTr("The authorization threshold is met. 'Ready' is not a flag someone set — it is re-derived from the signed log, so every client agrees without trusting a coordinator.") },
        { id: "submit", title: qsTr("Cross the boundary"), summary: qsTr("The assembled transaction leaves the room and is submitted on-chain. This is the one place the conversation boundary is crossed; the client names what became public and what stayed inside.") },
        { id: "settle", title: qsTr("Settle and record"), summary: qsTr("The transaction settles and the room reads the result back. Facts the room shows (balances, confirmations) carry a verification grade so a claim about the world is never taken on faith.") },
    ]

    readonly property var claims: [
        { step: "open-room", kind: "protects", title: qsTr("A later joiner cannot read earlier messages"), body: qsTr("Membership is epoch-based: admitting a member re-keys the room forward, so someone added mid-conversation reads from their epoch on and nothing before it. Removal rotates the epoch immediately."), requirement: "F-16", test: "module/tests/probes/probe_epoch_new_member_disjoint.nim", credibility: "imperative" },
        { step: "open-room", kind: "protects", title: qsTr("One identity to authorize, one to encrypt, provably the same person"), body: qsTr("Each member carries two keypairs — a secp256k1 authorization key (the one that signs transactions) and an Ed25519/X25519 encryption key — joined by a signed link statement the core verifies when it ingests the member, so the two cannot be silently mismatched."), requirement: "F-14", test: "module/tests/binding_test.nim", credibility: "imperative" },
        { step: "open-room", kind: "protects", title: qsTr("Nothing on the room's topic says who is in it"), body: qsTr("Everything published on a room's content topic is readable by the store node and any subscriber, so none of it names a member. A join request is sealed to a join key the room announces, so only members read who is asking; each key grant is sealed whole to one member, so no roster travels; and no envelope carries its epoch number. The store node still sees that someone asked to join, and how many members an admit re-keyed."), requirement: "FS-7", test: "module/tests/store_node_view_test.nim", credibility: "imperative" },
        { step: "open-room", kind: "others-leak", title: qsTr("A hosted chat backend sees the whole room"), body: qsTr("In a conventional hosted group chat, the server holds the membership roster and sees message timing directly — the room's shape is the operator's data."), system: "a hosted group-chat backend", observer: "the server operator" },
        { step: "open-room", kind: "gap", title: qsTr("The store node still sees the conversation graph"), body: qsTr("Content is encrypted, but a store node still sees the room's content topic, the timing and size of publishes and fetches, and each frame's kind — so that someone asked to join, and how many members an admit re-keyed — the conversation graph, pseudonymously. Reading is the half no setting hides yet: each fetch names the room's topic from the reader's own address. It never sees who is in the room (FS-7). This surface names that limit rather than claiming to hide it (FS-9)."), fix: qsTr("route through the Logos transport-layer mixnet. Sends can ride it now: delivery 0.3's sender anonymity, behind muster's mix setting (off by default), takes each publish over three mix hops to an exit, so a store node that does not also run the path's mix nodes no longer learns which node published. Fetches, the store queries that name a room's topic from the reader's own address, have no mix path; and on logos.dev most mix nodes are run by the store nodes' own operator"), status: "partial", spec_stage: "raw (LOGOS-MIXNET); delivery 0.3 ships sender anonymity, send-only, no cover traffic (docs/labbook/mixnet-on-delivery-03.md)", credibility: "exposed", party: qsTr("the store node operator (sees which topics a client fetches, and when; which topics it publishes to, and when, unless the mix setting is on; each frame's size and kind)") },
        { step: "propose", kind: "protects", title: qsTr("You sign what you saw, not what a screen claimed"), body: qsTr("The client independently re-derives the materialization from the displayed effect and refuses to sign if they disagree. The review target and the signing target are provably the same bytes; this check lives in the core and cannot be disabled."), requirement: "F-4", test: "module/tests/probes/probe_materialization_mismatch_refused.nim", credibility: "imperative" },
        { step: "propose", kind: "protects", title: qsTr("A signature is worthless anywhere but here"), body: qsTr("Every signing payload commits to the execution environment, the account, the serialization slot, and an expiry — so a signature captured here cannot be replayed against another chain, account, or slot."), requirement: "F-5", test: "module/tests/probes/probe_replay_binding_field_binds.nim", credibility: "imperative" },
        { step: "propose", kind: "protects", title: qsTr("Nothing is signed whose inputs can't be accounted for"), body: qsTr("The signing payload commits to a provenance record naming, for every input that reached the signed bytes, its class and its position in the log. Signing is refused when any input's origin is unaccountable."), requirement: "F-20", test: "module/tests/probes/probe_provenance_refusal_stepper.nim", credibility: "imperative" },
        { step: "propose", kind: "others-leak", title: qsTr("Blind signing trusts the screen that drew the hash"), body: qsTr("A browser wallet asked to sign a hash handed to it by a dApp cannot re-derive what that hash authorizes — the signer trusts the requesting page's rendering, which is exactly the gap F-4 closes."), system: "a browser wallet approving a dApp-supplied hash", observer: "the signer, who cannot verify what the hash authorizes" },
        { step: "propose", kind: "gap", title: qsTr("Schema identity is ours until the platform's profile ratifies"), body: qsTr("Signing-path bytes are deterministic and domain-separated (invariant 5). But which profile derives a schema's identity is still hand-assigned ids in v0; a ratified cdCDDLe schema-root profile would let a second module re-derive our schema identity without trusting our ids (ADR-009)."), fix: qsTr("adopt cdCDDLe schema roots in the profile field once LOGOS-MODULE-HASH-PROFILE ratifies — no format migration, the field already carries it"), status: "specified", spec_stage: "draft (unmerged, logos-co/logos-lips branch draft/logos-core-module-specs)", credibility: "motivational", party: qsTr("the module authors — hand-assigned schema ids are a promise not to collide, until cdCDDLe roots replace them") },
        { step: "collect", kind: "protects", title: qsTr("The core never interprets a contribution — the driver does"), body: qsTr("The core routes opaque contribution bytes and asks the driver what they mean. Rounds, serialization domain, threshold, and finality are all driver-described, never hardcoded, so a new coordination policy is a new driver, not a core change."), requirement: "F-6", test: "module/tests/probes/probe_core_opaque_routing_stepper.nim", credibility: "imperative" },
        { step: "collect", kind: "protects", title: qsTr("A non-owner signature never counts"), body: qsTr("A contribution from someone who is not an authorizer for this intent is refused, and a duplicate from the same authorizer folds only once — the threshold reflects real, distinct authorizations."), requirement: "FS-2", test: "module/tests/coordination_surface_test.nim", credibility: "imperative" },
        { step: "collect", kind: "protects", title: qsTr("Every driver passes one conformance suite"), body: qsTr("Stub, Safe, and threshold drivers are all graded by the same conformance suite; a driver feature does not merge with it red, so the coordination guarantees hold identically whichever driver a room runs."), requirement: "S-1", test: "module/tests/conformance_test.nim", credibility: "imperative" },
        { step: "collect", kind: "others-leak", title: qsTr("A hosted coordination service sees every proposal and signer"), body: qsTr("A hosted multisig transaction service watches proposals accumulate signatures before anything is on-chain — the operator sees who is coordinating what, in the clear. Muster assembles and submits client-side instead, with no such service."), system: "a hosted multisig transaction service", observer: "the service operator" },
        { step: "collect", kind: "gap", title: qsTr("FROST runs in the room, but its arithmetic is demo-grade"), body: qsTr("The genuinely multi-round protocol is built: ChillDKG makes the key in the room and BIP-445 FROST signs over two rounds of the room's log, held to the drafts' vectors and settled on a real Bitcoin Core regtest as one BIP-340 signature (phase_d_exit_test) and on a LEZ chain. But the group arithmetic is not constant time: it branches on secret values, so its timing can leak a share to anything that can time the signer's machine. It is demo-grade, behind the same production gate as MPC."), fix: qsTr("a constant-time FROST implementation (a reviewed library such as secp256k1-zkp's) behind the same keystore operations (S7), before it signs for real funds"), status: "partial", credibility: "exposed", party: qsTr("anything that can time the signer's machine while it signs (co-located software, a shared host)") },
        { step: "executable", kind: "protects", title: qsTr("State is re-derived, never asserted"), body: qsTr("'Ready' is a reduction over the signed log (state = reduce(log)), rebuilt from log plus keys on a cold start. Nothing exists that cannot be rebuilt, so no coordinator's say-so is trusted for whether the threshold is met."), requirement: "R-3", test: "module/tests/probes/probe_state_cold_start_matches.nim", credibility: "imperative" },
        { step: "executable", kind: "protects", title: qsTr("Duplicated or reordered messages converge to the same state"), body: qsTr("Reducers are idempotent and order-insensitive up to a deterministic tiebreak, so a message delivered twice or out of order by the transport still lands every client on identical state."), requirement: "R-2", test: "module/tests/probes/probe_convergence_reorder_stepper.nim", credibility: "imperative" },
        { step: "executable", kind: "others-leak", title: qsTr("A server-authoritative coordinator both holds and reads the tally"), body: qsTr("When a server owns the canonical 'ready' state, every client trusts its count — and the same server can read the running tally at will. Muster's threshold is re-derived locally by each client from the shared log."), system: "a server-authoritative coordination backend", observer: "the coordinator, which both holds and can read the tally" },
        { step: "executable", kind: "gap", title: qsTr("Cold-start re-derivation is not yet incremental"), body: qsTr("Re-deriving state replays the log; until log snapshotting lands, that is linear in the log length rather than snapshot-plus-tail, so the P-2/P-5 cold-start and reduction targets are not yet met or benchmarked."), fix: qsTr("log snapshotting (periodic snapshot + tail replay) to make reduction incremental after the first pass (P6)"), status: "none", credibility: "not-applicable" },
        { step: "submit", kind: "protects", title: qsTr("The submit is a real, client-side on-chain call"), body: qsTr("Submit re-derives and signs the transaction locally and calls the chain directly (a real Safe execTransaction against the on-chain contract) — there is no hosted transaction service and no server-side application state in the path."), requirement: "FS-1", test: "module/tests/safe_anvil_e2e.nim", credibility: "imperative" },
        { step: "submit", kind: "protects", title: qsTr("The one place the ground changes is named"), body: qsTr("Crossing the boundary is the single moment the interface's visual ground changes, and the submitted card names what became public versus what stayed inside — the boundary is drawn, not left for the user to infer."), requirement: "U-2", test: "ui/tests/muster-ui-test.mjs", credibility: "imperative" },
        { step: "submit", kind: "others-leak", title: qsTr("The chain records the signers, forever"), body: qsTr("The on-chain transaction records the signer addresses permanently and publicly — this is real and unavoidable at settlement, which is why the boundary crossing is made explicit rather than hidden."), system: "the public blockchain", observer: "anyone reading the chain" },
        { step: "submit", kind: "gap", title: qsTr("Keeping signers unlinkable at settlement needs an aggregate-signature rail"), body: qsTr("Inside the room every member knows who approved — that is the design (ADR-015). Outside it, the Safe and the script multisigs (P2WSH, tapscript) name their signers to anyone reading the chain once the transaction settles. The aggregate-signature families are built — a FROST account on Bitcoin (btc.frost-bip445) and on the LEZ (lez.frost-public-account) settles as one signature — but a room has to choose them, and every other rail still names its signers."), fix: qsTr("settle through an aggregate-signature family (built: btc.frost-bip445, lez.frost-public-account), so chain observers see that the threshold was met, not which owners signed; the Safe and the script multisigs name signers by construction"), status: "partial", credibility: "exposed", party: qsTr("anyone reading the chain — the settled transaction names the signers") },
        { step: "submit", kind: "protects", title: qsTr("In a split, you pay exactly the share you agreed"), body: qsTr("The payment your wallet signs is derived from the split everyone agreed to: your share, to the address in it, in its asset, on its chain. There is no amount or address to type. Nothing is sent before everyone named has agreed, twice, for someone else's share, or after the agreement expired."), requirement: "F-4", test: "module/tests/probes/probe_split_payment_derived_stepper.nim", credibility: "imperative" },
        { step: "submit", kind: "protects", title: qsTr("A private split tells the chain only that private transfers happened"), body: qsTr("On the LEZ's private rail each person pays shielded to shielded, so the chain sees no payer, no payee and no amount. A payment from a public account, which would name them, is refused rather than quietly allowed. The creditor finds each payment by scanning her own wallet for a note of exactly that share; every share is a different amount, a few base units apart, so no two can be confused."), requirement: "FS-9", test: "module/tests/split_lez_test.nim", credibility: "imperative" },
        { step: "submit", kind: "others-leak", title: qsTr("Settling a split with public transfers links the whole group"), body: qsTr("When each friend pays their share with an ordinary transfer, every payment puts payer, payee and amount on the chain. Several payments of similar amounts to one address, close together, tie the group to each other and to the bill, permanently."), system: "a bill split settled with public on-chain transfers (each friend sending their share to whoever paid)", observer: "anyone reading the chain" },
        { step: "settle", kind: "protects", title: qsTr("A fact about the world carries how it was checked"), body: qsTr("Facts the room shows (like a balance) carry a verification grade — verified-locally when the client re-checked the read itself, attested otherwise — always displayed. A read that fails raises; it never quietly renders as a zero."), requirement: "F-10", test: "module/tests/wallet_verify_test.nim", credibility: "imperative" },
        { step: "settle", kind: "others-leak", title: qsTr("A custodial balance API asks you to take its number on faith"), body: qsTr("A hosted or custodial balance endpoint returns a number you cannot independently check — you trust the provider. Muster earns the verified grade by re-running the proof against a user-configured node, in-process."), system: "a custodial or hosted balance API", observer: "the API provider" },
        { step: "settle", kind: "gap", title: qsTr("'Verified-locally' is proof-checked, not yet trustless end-to-end"), body: qsTr("A verified read checks a Merkle proof against a state root the client fetches from a user-configured RPC — it trusts that root. Making the root itself trustless needs a beacon light-client sidecar, which is deferred on infrastructure."), fix: qsTr("add the beacon light-client sidecar so the state root is verified against the beacon chain, not taken from the RPC (ADR-014, deferred)"), status: "partial", credibility: "motivational", party: qsTr("the supplier of the state root — until the beacon light-client sidecar, the root the proof is checked against is attested, not derived") },
        { step: "settle", kind: "protects", title: qsTr("A share counts as paid only when the person owed says so"), body: qsTr("Only the person who owes a share can report it paid, and only the person owed can confirm it, from their own read of the chain or their own scan. A report signed by anyone else never moves the split. A split is final when every share is confirmed, not when someone announces it."), requirement: "FS-7", test: "module/tests/probes/probe_split_authorship_stepper.nim", credibility: "imperative" },
        { step: "settle", kind: "gap", title: qsTr("Nothing makes anyone pay their share"), body: qsTr("The room records who agreed and who has paid, truthfully and only as each person disclosed it, but no contract holds the money. A split is a promise the group can see, not one the chain enforces."), fix: qsTr("a split with deposits: each person locks their share in an on-chain escrow when they agree, released to whoever paid the bill once the split settles"), status: "none", credibility: "motivational", party: qsTr("each person who owes a share (whether they pay is up to them)") },
        { step: "submit", kind: "protects", title: qsTr("A FROST spend looks like one signer's"), body: qsTr("A key made by the room's ChillDKG ceremony signs under FROST as one plain BIP-340 signature that libsecp256k1 accepts under the account's x-only key. On chain the spend is the witness a single-sig taproot spend has: nothing says it was a threshold, or which members signed (phase_d_exit_test, on Bitcoin Core regtest)."), requirement: "F-7", test: "module/tests/frost_dkg_sign_test.nim", credibility: "imperative" },
        { step: "propose", kind: "protects", title: qsTr("A Monero request pays only the payee's own subaddress"), body: qsTr("The payee's client proposes or agrees to an XMR request only when their own Monero wallet lists the address as theirs, it is on the agreed network, and it is not an integrated address. A request whose address fails Monero address validation for its chain is payable on no member's client, even after others agree to it."), requirement: "F-10", test: "module/tests/probes/probe_xmr_payto_stepper.nim", credibility: "imperative" },
        { step: "submit", kind: "protects", title: qsTr("Muster never spends from a Monero wallet: it calls only read and mint methods"), body: qsTr("On every path of an XMR request (propose, agree, show the link, \"I paid\", confirm, relaunch, a request on someone's behalf) Muster asks the wallet backend only for its status, its receive info, a fresh subaddress, its history and who is calling. It never asks it to build, sign or broadcast a transfer, or to change the wallet's roles; asked to pay, it refuses and sends nothing. The payer pays from their own wallet through a monero: link, and the keys stay in the wallet that holds them."), requirement: "FS-4", test: "module/tests/probes/probe_xmr_no_spend_stepper.nim", credibility: "imperative" },
        { step: "settle", kind: "protects", title: qsTr("A Monero payment counts only when the payee's own wallet sees exactly the share, 10 confirmations deep"), body: qsTr("A part of an XMR request is confirmed only from the payee's own wallet history: an incoming transfer to the request's subaddress, of exactly the share in atomic units, at least 10 blocks deep (Monero's unlock age). A debtor's \"I paid\", a txid alone, one atomic unit off, another subaddress, nine confirmations, or a busy or unanswered wallet never confirms it; an unanswered read is not yet known, never paid and never failed. One transfer confirms one part."), requirement: "F-10", test: "module/tests/probes/probe_xmr_confirm_stepper.nim", credibility: "imperative" },
        { step: "settle", kind: "protects", title: qsTr("A stagenet request is never settled by mainnet history"), body: qsTr("An XMR request is agreed on one Monero network. If the payee's open wallet is on another network, nothing is confirmed from it, even a perfect transfer 20 blocks deep; the client names the remedy (open the agreed network's wallet) instead."), requirement: "F-5", test: "module/tests/probes/probe_xmr_network_stepper.nim", credibility: "imperative" },
        { step: "submit", kind: "gap", title: qsTr("The payer's Monero node sees the wallet sync and the broadcast"), body: qsTr("Muster never touches the payer's transfer, but the wallet that sends it syncs through a Monero node (a remote one by default) and broadcasts through it. That node sees the wallet's sync requests and when the transfer is sent, from the payer's address. The chain itself shows no sender, receiver or amount."), fix: qsTr("run your own Monero node, or reach a remote one through a proxy (Tor or I2P), in the wallet you pay from; Muster does not choose this for the payer's wallet"), status: "partial", credibility: "exposed", party: qsTr("the payer's Monero node operator (sees the wallet's sync and the broadcast's timing, from the payer's address)") },
        { step: "settle", kind: "gap", title: qsTr("Modules loaded beside Muster can read the payee's Monero history"), body: qsTr("Muster confirms a payment by reading the payee's own wallet through Basecamp's Monero wallet backend. Its reads (history, receive info, subaddresses) take no wallet role, so any module loaded in the same Basecamp can make the same reads. Only confirming a send needs a role the person grants."), fix: qsTr("the wallet backend gating its reads by caller (a read role, or Basecamp's capability broker), so only a module the person allowed can read the history"), status: "none", credibility: "exposed", party: qsTr("modules loaded in the same Basecamp as Muster") },
    ]

    function forStep(stepId) {
        return root.claims.filter(function (c) { return c.step === stepId; });
    }

    function titleOf(stepId) {
        for (var i = 0; i < root.steps.length; ++i)
            if (root.steps[i].id === stepId)
                return root.steps[i].title;
        return stepId;
    }
}
