## LEZ v0.2.4 public transactions, as muster builds them (exo-3c9: the live binding).
## Held to vectors/lez-tx-v024, generated by LEZ's own types (lee / lee_core / common @
## v0.2.4) and lez-multisig's multisig_core — see that directory's SOURCE:
##   1. a public account id is SHA-256("/LEE/v0.3/AccountId/Public/" padded to 32 ‖ the
##      BIP-340 x-only key) — every key vector;
##   2. every multisig instruction, from muster's MultisigOp, is the program's risc0-serde
##      words exactly (a byte is a word, a u64 two, a vec its length then its items), and
##      the count-only layout's Propose drops only target_account_ids;
##   3. the message is borsh (program as 8 LE words · account ids · u128 nonces · words) and
##      its hash is SHA-256("/LEE/v0.3/Message/Public/" padded ‖ borsh) — a signer-less
##      create, an approve, an execute with a nonce beyond u64;
##   4. a BIP-340 signature with zero aux over that hash is the vector's; the transaction
##      borsh, its hash, and the base64 sendTransaction carries (LeeTransaction::Public)
##      are the vectors';
##   5. a program deployment (LeeTransaction::ProgramDeployment) and its hash;
##   6. the account list each instruction names: state PDA, signer, proposal PDA, then the
##      execute's target accounts; a create names the state PDA and the members, no signer.
## Needs the secp closure — see tests/README.md.

import std/[json, os, strutils, sequtils, base64]
import stint
import ../src/hashing/sha256
import ../src/bitcoin/keys
import ../src/bitcoin/tx             # toHex / hexToBytes
import ../src/lez/multisig
import ../src/lez/multisig_chain
import ../src/lez/tx as leztx

let v = parseJson(readFile(currentSourcePath.parentDir / "vectors" / "lez-tx-v024" / "vectors.json"))
proc words(n: JsonNode): seq[uint32] = n.getElems().mapIt(uint32(it.getBiggestInt()))
proc hb(s: string): seq[byte] = hexToBytes(s)
proc b32(x: byte): seq[byte] = newSeqWith(32, x)

# ── 1. account ids ────────────────────────────────────────────────────────────
var ids: seq[seq[byte]]
for k in v["keys"]:
  let secret = hb(k["secret"].getStr())
  doAssert xonlyPubKey(secret) == hb(k["xonly"].getStr())
  doAssert publicAccountId(hb(k["xonly"].getStr())) == hb(k["account_id"].getStr()), "account id"
  ids.add hb(k["account_id"].getStr())
echo "1. public account ids: SHA-256(/LEE/v0.3/AccountId/Public/ ‖ x-only) OK"

# ── 2. instruction words ──────────────────────────────────────────────────────
let ck = b32(7)
let token = hb("ccc4713e2b5ecdff37b0c67c295369effc04b7e8994eb11c3f410bb226b82e9b")
let transfer = words(v["token_transfer_200_words"])
let (vault, to, seed) = (b32(0xa3), b32(0xa4), b32(0x5e))
let action = LezAction(target: token, instruction: transfer, accounts: @[vault, to], pdaSeeds: @[seed],
                       authorized: @[0'u8])
let ops = {
  "create": createOp(ck, 2, @[ids[0], ids[1], ids[2]]),
  "propose": proposeOp(ck, 2, action),
  "approve": approveOp(ck, 2),
  "reject": rejectOp(ck, 3),
  "execute": executeOp(ck, 2, @[vault, to]),
  "propose-add-member": proposeConfigOp(ck, 4, ConfigAction(kind: caAddMember, member: ids[3])),
  "propose-remove-member": proposeConfigOp(ck, 5, ConfigAction(kind: caRemoveMember, member: ids[2])),
  "propose-change-threshold": proposeConfigOp(ck, 6, ConfigAction(kind: caChangeThreshold, threshold: 3)),
}
for i in v["instructions"]:
  let name = i["name"].getStr()
  var op: MultisigOp
  for (n, o) in ops:
    if n == name: op = o
  doAssert instructionWords(op, plAccountIds) == words(i["words"]), "instruction " & name
let proposeOld = instructionWords(proposeOp(ck, 2, action), plCountOnly)
let proposeNew = instructionWords(proposeOp(ck, 2, action), plAccountIds)
doAssert proposeNew.len - proposeOld.len == 1 + 2 * 32, "count-only drops only target_account_ids"
doAssert instructionWords(approveOp(ck, 2), plCountOnly) == instructionWords(approveOp(ck, 2), plAccountIds)
echo "2. every multisig instruction is the program's risc0-serde words; count-only drops only the ids OK"

# ── 3 + 4. messages, signatures, transactions ─────────────────────────────────
let secrets = v["keys"].getElems().mapIt(hb(it["secret"].getStr()))
for t in v["txs"]:
  let name = t["name"].getStr()
  let m = LezMessage(program: hb(t["program"].getStr()),
                     accounts: t["accounts"].getElems().mapIt(hb(it.getStr())),
                     nonces: t["nonces"].getElems().mapIt(parse(it.getStr(), UInt128)),
                     words: words(t["instruction_words"]))
  doAssert messageBorsh(m) == hb(t["message_borsh"].getStr()), name & ": message borsh"
  let h = messageHash(m)
  doAssert toHex(@h) == t["message_hash"].getStr(), name & ": message hash"
  var ws: seq[LezWitness]
  for s in t["signatures"]:
    let sig = schnorrSign(secrets[0], h, newSeq[byte](32))     # the signer is key 0x11
    doAssert toHex(sig) == s.getStr(), name & ": BIP-340 with zero aux"
    doAssert schnorrVerify(sig, h, xonlyPubKey(secrets[0]))
    ws.add LezWitness(signature: sig, xonly: xonlyPubKey(secrets[0]))
  doAssert publicTxBorsh(m, ws) == hb(t["tx_borsh"].getStr()), name & ": transaction borsh"
  doAssert publicTxHash(m, ws) == t["tx_hash"].getStr() and t["tx_hash"].getStr() == t["lee_tx_hash"].getStr()
  doAssert encode(leeTxPublic(m, ws)) == t["lee_tx_base64"].getStr(), name & ": sendTransaction payload"
echo "3. messages: borsh + domain-separated hash (a u128 nonce beyond u64 included) OK"
echo "4. BIP-340 witnesses, the transaction borsh, its hash, the sendTransaction base64 OK"

# ── 5. program deployment ─────────────────────────────────────────────────────
let code = hb(v["deploy"]["bytecode"].getStr())
doAssert encode(leeTxDeploy(code)) == v["deploy"]["lee_tx_base64"].getStr()
doAssert deployTxHash(code) == v["deploy"]["lee_tx_hash"].getStr()
echo "5. program deployment: payload + hash OK"

# ── 6. the accounts each instruction names ────────────────────────────────────
let prog = hb("2ced3d301a4d1cd5db6cad9c428b9f3463155073f8bacf73179c6ea6536de4c7")
let state = statePda(psLee02, prog, ck)
let me = ids[0]
doAssert opAccounts(psLee02, prog, createOp(ck, 2, ids[0 .. 2]), @[]) == @[state] & ids[0 .. 2]
for (op, idx) in [(proposeOp(ck, 2, action), 2'u64), (approveOp(ck, 2), 2'u64), (rejectOp(ck, 3), 3'u64),
                  (proposeConfigOp(ck, 6, ConfigAction(kind: caChangeThreshold, threshold: 3)), 6'u64)]:
  doAssert opAccounts(psLee02, prog, op, me) == @[state, me, proposalPda(psLee02, prog, ck, idx)], $op.kind
doAssert opAccounts(psLee02, prog, executeOp(ck, 2, @[vault, to]), me) ==
         @[state, me, proposalPda(psLee02, prog, ck, 2), vault, to]
doAssert not opSigned(createOp(ck, 2, ids[0 .. 2])) and opSigned(approveOp(ck, 2))
echo "6. accounts: state PDA, signer, proposal PDA (+ execute targets); a create names the members, unsigned OK"

echo "lez_tx_test: LEZ v0.2.4 public transactions, byte for byte against LEZ's own types — all OK"
