## LEZ v0.3.0 public transactions, as muster builds them (exo-eb6.4 L3). Held to
## vectors/lez-tx-v030, generated by LEZ's own types (lee / lee_core / common @ v0.3.0) —
## see that directory's SOURCE:
##   1. a public account id is unchanged from v0.2.4: SHA-256("/LEE/v0.3/AccountId/Public/"
##      padded ‖ the BIP-340 x-only key) — every key vector;
##   2. the native token program is account 0, a native transfer selects both rows' native
##      shard, and its instruction is borsh Transfer { amount: u128 };
##   3. the message is borsh (program account · shard selectors · u128 nonces · instruction
##      bytes · Option<FeeDeclaration>) and its hash is SHA-256("/LEE/v0.3/Message/Public/"
##      padded ‖ borsh): self-pay, a co-signing payer (its nonce last), the fee-exempt None;
##   4. a BIP-340 signature with zero aux over that hash is the vector's, for every signer,
##      the payer included; the transaction borsh, its hash, and the base64 sendTransaction
##      carries (LeeTransaction::Public) are the vectors';
##   5. the fee muster declares by default is the LEZ wallet's: gas_limit 2_000_000, tip 0,
##      max_fee (2_000_000 + 100_000) × 64.
## Needs the secp closure — see tests/README.md.

import std/[json, os, strutils, sequtils, base64, options]
import stint
import ../src/bitcoin/keys
import ../src/bitcoin/tx             # toHex / hexToBytes
import ../src/lez/tx as leztx
import ../src/lez/account_view

let v = parseJson(readFile(currentSourcePath.parentDir / "vectors" / "lez-tx-v030" / "vectors.json"))
proc hb(s: string): seq[byte] = hexToBytes(s)

# ── 1. account ids ────────────────────────────────────────────────────────────
var secrets, ids: seq[seq[byte]]
for k in v["keys"]:
  let secret = hb(k["secret"].getStr())
  doAssert xonlyPubKey(secret) == hb(k["xonly"].getStr())
  doAssert publicAccountId(xonlyPubKey(secret)) == hb(k["account_id"].getStr())
  secrets.add secret
  ids.add hb(k["account_id"].getStr())
echo "1. public account ids: unchanged from v0.2.4 OK"

# ── 2. the native token program and its transfer ─────────────────────────────
doAssert NativeTokenProgram == hb(v["native_token_program"].getStr())
doAssert nativeTransfer(parse("1000", UInt128)) == hb(v["txs"][0]["instruction"].getStr())
doAssert nativeShard(ids[0]) == LezShard(account: ids[0], program: NativeTokenProgram)
echo "2. native transfer: program account 0, both native shards, borsh Transfer { amount } OK"

# ── 3 + 4. messages, signatures, transactions ─────────────────────────────────
proc keyFor(id: seq[byte]): seq[byte] =
  for i, x in ids:
    if x == id: return secrets[i]
  raise newException(ValueError, "no key for " & toHex(id))

for t in v["txs"]:
  let name = t["name"].getStr()
  var m = LezMessage3(programAccount: hb(t["program_account"].getStr()),
                      shards: t["selectors"].getElems().mapIt(
                        LezShard(account: hb(it["account"].getStr()), program: hb(it["program"].getStr()))),
                      nonces: t["nonces"].getElems().mapIt(parse(it.getStr(), UInt128)),
                      instruction: hb(t["instruction"].getStr()))
  let f = t["fee"]
  if f.kind != JNull:
    m.fee = some LezFee(payer: hb(f["payer"].getStr()),
                        gasLimit: parseBiggestUInt(f["gas_limit"].getStr()).uint64,
                        tip: parseBiggestUInt(f["tip"].getStr()).uint64,
                        maxFee: parse(f["max_fee"].getStr(), UInt128))
  doAssert messageBorsh(m) == hb(t["message_borsh"].getStr()), name & ": message borsh"
  let h = messageHash(m)
  doAssert toHex(@h) == t["message_hash"].getStr(), name & ": message hash"
  # the signers: the sender (the first row), then a payer that is not already a signer
  var signers = @[m.shards[0].account]
  if m.fee.isSome and m.fee.get.payer notin signers: signers.add m.fee.get.payer
  doAssert signers.len == t["signatures"].len, name & ": one signature per signer"
  var ws: seq[LezWitness]
  for i, s in t["signatures"].getElems():
    let sk = keyFor(signers[i])
    let sig = schnorrSign(sk, h, newSeq[byte](32))
    doAssert toHex(sig) == s.getStr(), name & ": BIP-340 with zero aux, signer " & $i
    doAssert schnorrVerify(sig, h, xonlyPubKey(sk))
    ws.add LezWitness(signature: sig, xonly: xonlyPubKey(sk))
  doAssert publicTxBorsh(m, ws) == hb(t["tx_borsh"].getStr()), name & ": transaction borsh"
  doAssert publicTxHash(m, ws) == t["tx_hash"].getStr() and t["tx_hash"].getStr() == t["lee_tx_hash"].getStr()
  doAssert encode(leeTxPublic(m, ws)) == t["lee_tx_base64"].getStr(), name & ": sendTransaction payload"
echo "3. messages: borsh + domain-separated hash; self-pay, a co-signing payer, fee-exempt OK"
echo "4. BIP-340 witnesses (the payer's included), the transaction borsh, its hash, the base64 OK"

# ── 5. the default fee ────────────────────────────────────────────────────────
let d = defaultFee(ids[0])
doAssert d.payer == ids[0] and d.tip == 0
doAssert $d.gasLimit == v["default_gas_limit"].getStr() and $d.maxFee == v["default_max_fee"].getStr()
doAssert $d.maxFee == "134400000", "what the LEZ CLI declared on the local v0.3 zone"
echo "5. the default fee is the LEZ wallet's: gas 2_000_000, tip 0, max_fee 134_400_000 OK"

# ── 6. an account as the v0.3 sequencer reports it ───────────────────────────
block:
  # getAccount on a local v0.3.0 zone (2026-10-01), the funder after sending 1000 and
  # paying a 2_968 fee (well under its 134_400_000 cap): a nonce and the account's program
  # shards; the native balance is the 16-byte LE shard of the native program (account 0,
  # "1111…" in base58), and an account with no shards holds nothing
  let v3 = parseJson("""{"nonce":1,"data":{"shards":{"11111111111111111111111111111111":[128,112,198,164,126,141,3,0,0,0,0,0,0,0,0,0]}}}""")
  let a = accountStateOf(v3)
  doAssert $a.nonce == "1" and $a.balance == "999999999996032"
  doAssert a.shards.len == 1 and a.shards[0].program == NativeTokenProgram
  doAssert a.owner.len == 0 and a.data.len == 0, "v0.3 has no single owner or data"
  doAssert not a.fresh and a.v3, "the zone's line is read off the shape"
  let empty = accountStateOf(parseJson("""{"nonce":0,"data":{"shards":{}}}"""))
  doAssert $empty.balance == "0" and empty.fresh
  # the v0.2.4 shape still reads as before
  let v2 = accountStateOf(parseJson("""{"program_owner":[1,0,0,0,0,0,0,0],"balance":5,"data":[7,8],"nonce":"3"}"""))
  doAssert v2.owner.len == 32 and v2.owner[0] == 1 and $v2.balance == "5" and v2.data == @[7'u8, 8] and $v2.nonce == "3"
  doAssert not v2.fresh and not v2.v3
echo "6. getAccount on v0.3: nonce + program shards, the native balance from the native shard; v0.2.4 still reads OK"

echo "lez_tx_v030_test: LEZ v0.3.0 public transactions, byte for byte against LEZ's own types — all OK"
